service: circulo-de-credito

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: staging
  region: us-east-1
  layers:
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pydantic:1
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-boto3:19
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-SQLAlchemy:16
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-psycopg2-binary:1
    - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-requests:16

  environment:
    eventType: mx.com.circulodecredito.eva
    webhookUrl: https://1ie4wrhmtj.execute-api.us-east-1.amazonaws.com/webhook
    BASE_URL: https://services.circulodecredito.com.mx/sandbox
    API_KEY: Oaodh8pDqM2nTVzB7fBh3RGopqDGaJMI
    HOST: financial-services-00.cyu0flmjq123.us-east-1.rds.amazonaws.com
    DB: th_financial_services
    USER: admin_pgsql
    PASSWORD: SSf2nKe9ptMVkA2wHTW
    DRIVER: postgresql+psycopg2
    SQS_URL: https://sqs.us-east-1.amazonaws.com/018796182887/my-sqs-webhook-queue.fifo
    SECRET_KEY: circulodecredito
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage 
      Resource:
        - arn:aws:sqs:us-east-1:018796182887:my-sqs-webhook-queue.fifo
 
   
custom:
  localstack:
    debug: true
    stages:
      - local
package:
  patterns:
    - '!**/__pycache__/**'
    - '!node_modules/**'
    - '!venv/**'
    - '!.vscode'
    - '!.git/**'
    - '!provision/**'
    - '!.idea/**'
    - '!assets/**' 
    - '!package-lock.json'
    - '!package.json'
    - '!event.json'
    - '!eventdos.json'
    - '!console_exec.txt'
    - '!docker-compose.yml' 
plugins:
  - serverless-localstack

functions:
  health_check:
    handler: api.health_check
    events:
      - httpApi:
          method: GET
          path: /health-check

  create_subscriptions:
    handler: src.interfaces.api.subscriptions.create_subscription_handler.handler
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0

    events:
      - httpApi:
          method: POST
          path: /suscription
  
  get_subscriptions:
    handler: src.interfaces.api.subscriptions.get_subscriptions_handler.handler
    events:
      - httpApi:
          method: GET
          path: /suscriptions

  get_subscription:
    handler: src.interfaces.api.subscriptions.get_subscription_handler.handler
    events:
      - httpApi:
          method: GET
          path: /suscription/{id}

  get_subscription_db:
    handler: src.interfaces.api.subscriptions.get_subscriptions_db_handler.handler
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - httpApi:
          method: GET
          path: /suscription

  delete_subscription:
    handler: src.interfaces.api.subscriptions.delete_subscription_handler.handler
    events:
      - httpApi:
          method: DELETE
          path: /suscription/{id}

  create_eva_auth:
    handler: src.interfaces.api.eva.imss.create_eva_authorization_handler.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - httpApi:
          method: POST
          path: /create-eva-imss-authorization

  create_eva_auth_issste:
    handler: src.interfaces.api.eva.issste.create_eva_authorization_handler.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - httpApi:
          method: POST
          path: /create-eva-issste-authorization

  get_eva_inquiry_id:
    handler: src.interfaces.api.eva.imss.get_eva_inquiry_id_handler.handler
    events:
      - httpApi:
          method: GET
          path: /get-eva-imss-employee/{id}

  webhook:
    handler: src.interfaces.webhook.webhook_handler.handler
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - httpApi:
          method: POST
          path: /webhook
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
 

  processSQSMessage:
    handler: src.interfaces.webhook.webhook_handler.processSQSMessage
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
  
  prospect_get_eva:
    handler: src.interfaces.api.prospect.get_prospect_eva.handler
    vpc:
      securityGroupIds:
        - sg-0a3c34fd0640b34c0
      subnetIds:
        - subnet-0d0d6021cd95afae6
        - subnet-092dc363cdd01e346
        - subnet-0dc1783b05636f6e0
    events:
      - httpApi:
          method: GET
          path: /get-eva-prospect/{id}
   

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-sqs-webhook-queue.fifo
        VisibilityTimeout: 3000
        MessageRetentionPeriod: 60
        ContentBasedDeduplication: true
        FifoQueue: true
